name: Analyse
version: '${version}'
main: net.analyse.plugin.AnalysePlugin
api-version: 1.13
folia-supported: true
softdepend:
  - PlaceholderAPI
  - floodgate
commands:
  analyse:
    description: The main command
