name: Analyse
version: '${version}'
main: io.tebex.analytics.AnalyticsPlugin
website: "https://tebex.io"
description: "The Spigot plugin for Tebex Analytics."
api-version: 1.13
folia-supported: true
softdepend:
  - PlaceholderAPI
  - floodgate
commands:
  analyse:
    description: The main command
