name: Analytics
version: '${version}'
main: io.tebex.analytics.AnalyticsPlugin
website: "https://tebex.io"
description: "The Bungeecord plugin for Tebex Analytics."
commands:
  analyse:
    description: The main command